// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOI3sp41fIAved0spxr8JtPVD-6TWd4dY',
    appId: '1:722013021729:web:2df3cbc06c2ac97d05a560',
    messagingSenderId: '722013021729',
    projectId: 'glassesgo-e00ba',
    authDomain: 'glassesgo-e00ba.firebaseapp.com',
    storageBucket: 'glassesgo-e00ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrs_pUVXvnP8e6hR6dvRSQfqVXw5cPBRA',
    appId: '1:722013021729:android:88443bd9c94439f805a560',
    messagingSenderId: '722013021729',
    projectId: 'glassesgo-e00ba',
    storageBucket: 'glassesgo-e00ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0pcQk3eXYGDuFfrBLu8gkAqxPdJIhsTE',
    appId: '1:722013021729:ios:16096421ba934ee205a560',
    messagingSenderId: '722013021729',
    projectId: 'glassesgo-e00ba',
    storageBucket: 'glassesgo-e00ba.appspot.com',
    iosBundleId: 'com.example.glassesgo',
  );
}
